# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget SeetaFaceLandmarker)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target SeetaFaceLandmarker
add_library(SeetaFaceLandmarker SHARED IMPORTED)

# Import target "SeetaFaceLandmarker" for configuration "Debug"
set_property(TARGET SeetaFaceLandmarker APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SeetaFaceLandmarker PROPERTIES
  IMPORTED_IMPLIB_DEBUG "G:/face/bulid/lib/Debug/SeetaFaceLandmarker-d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "SeetaNet"
  IMPORTED_LOCATION_DEBUG "G:/face/bulid/bin/Debug/SeetaFaceLandmarker-d.dll"
  )

# Import target "SeetaFaceLandmarker" for configuration "Release"
set_property(TARGET SeetaFaceLandmarker APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SeetaFaceLandmarker PROPERTIES
  IMPORTED_IMPLIB_RELEASE "G:/face/bulid/lib/Release/SeetaFaceLandmarker.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "SeetaNet"
  IMPORTED_LOCATION_RELEASE "G:/face/bulid/bin/Release/SeetaFaceLandmarker.dll"
  )

# Import target "SeetaFaceLandmarker" for configuration "MinSizeRel"
set_property(TARGET SeetaFaceLandmarker APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SeetaFaceLandmarker PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "G:/face/bulid/lib/MinSizeRel/SeetaFaceLandmarker.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "SeetaNet"
  IMPORTED_LOCATION_MINSIZEREL "G:/face/bulid/bin/MinSizeRel/SeetaFaceLandmarker.dll"
  )

# Import target "SeetaFaceLandmarker" for configuration "RelWithDebInfo"
set_property(TARGET SeetaFaceLandmarker APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SeetaFaceLandmarker PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "G:/face/bulid/lib/RelWithDebInfo/SeetaFaceLandmarker.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "SeetaNet"
  IMPORTED_LOCATION_RELWITHDEBINFO "G:/face/bulid/bin/RelWithDebInfo/SeetaFaceLandmarker.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
